"""add name column to agents

Revision ID: 74effeb1971b
Revises: b2a126a30a14
Create Date: 2026-05-26 15:57:59.692217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74effeb1971b'
down_revision = 'b2a126a30a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('name', sa.String(length=150), nullable=False))
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_column('agents', 'name')
    # ### end Alembic commands ###