"""add_assigned_region_to_users

Revision ID: b50c7d568614
Revises: efc87e659e91
Create Date: 2026-07-20 12:28:58.629733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50c7d568614'
down_revision = 'efc87e659e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assigned_region', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'assigned_region')
    # ### end Alembic commands ###