"""Add delivery disputes table

Revision ID: b767edf4b9ac
Revises: b50c7d568614
Create Date: 2026-07-27 20:54:56.686151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b767edf4b9ac'
down_revision = 'b50c7d568614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###