"""Add delivery disputes table

Revision ID: ef87bba519a2
Revises: b767edf4b9ac
Create Date: 2026-07-31 07:16:57.073971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef87bba519a2'
down_revision = 'b767edf4b9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###