"""Add push subscriptions table

Revision ID: efc87e659e91
Revises: 74effeb1971b
Create Date: 2026-06-08 14:30:18.119076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc87e659e91'
down_revision = '74effeb1971b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###