from enum import StrEnum


class RoleCode(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    MANUFACTURER = "MANUFACTURER"
    WAREHOUSE_OFFICER = "WAREHOUSE_OFFICER"
    DISTRIBUTION_TEAM = "DISTRIBUTION_TEAM"
    MANAGER = "MANAGER"
    HUB_OFFICER = "HUB_OFFICER"
    AGENT = "AGENT"


class BatchStatus(StrEnum):
    AWAITING_RELEASE= "AWAITING_RELEASE"
    RELEASED_TO_WAREHOUSE = "RELEASED_TO_WAREHOUSE"
    RECEIVED_AT_WAREHOUSE = "RECEIVED_AT_WAREHOUSE"
    CANCELLED = "CANCELLED"


class LocationType(StrEnum):
    MANUFACTURER = "MANUFACTURER"
    WAREHOUSE = "WAREHOUSE"
    HUB = "HUB"
    AGENT = "AGENT"


class TransactionType(StrEnum):
    PRODUCTION = "PRODUCTION"
    WAREHOUSE_RECEIPT = "WAREHOUSE_RECEIPT"
    ALLOCATION = "ALLOCATION"
    DISPATCH = "DISPATCH"
    RECEIPT = "RECEIPT"
    TRANSFER = "TRANSFER"
    ADJUSTMENT_REVERSAL = "ADJUSTMENT_REVERSAL"
    AGENT_ALLOCATION = "AGENT_ALLOCATION"


class RequestStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FULFILLED = "FULFILLED"
    CANCELLED = "CANCELLED"


class DispatchStatus(StrEnum):
    DRAFT = "DRAFT"
    DISPATCHED = "DISPATCHED"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    RECEIVED = "RECEIVED"
    CANCELLED = "CANCELLED"
